services:
  - type: web
    name: fraud-pipeline
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    healthCheckPath: /docs
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
